### ISSUE TITLE
Tests where expected result is unknown

### ISSUE THREAD

**Issue by ezedh** [kotanetes/go-test-it#5]
Hello! I'm creating regression tests using your tool for student quizzes. The thing is that in some cases we do not know what the body of the result will be and we only care about the status code.

It would be really great if there is an option to "ignore" that assertion, for example, if it is not present in the JSON.
I was thinking of this slight modification [here](https://github.com/kotanetes/go-test-it/blob/master/model2/model.go#L272):
```go
if s.ExpectedResult && !cmp.Equal(s.ExpectedResult, s.ReturnedResult, cmp.Reporter(&r))
```

In that case, it will only compare the result if it's present.

**Comment by kotanetes** [comment]
I didn't consider a scenario that ignore the assertion. The fix has been pushed with latest tag. Please use the latest version
https://github.com/kotanetes/go-test-it/releases/tag/v0.1.3
